### ISSUE TITLE
Missing ses key step?

### ISSUE THREAD

**Issue by hakunin** [michelson/chaskiq-newsletters#8]
Hi, I am just trying out chaskiq and it says

```
Chaskiq::ConfigError
 ses_access_key config key not found, add it in Chaskiq::Config.setup initializer 
```

it seems to be missing from the install. 

PS: Is there a way to play with it without such key?

**Comment by michelson** [comment]
Hi @hakunin , 
Take a look at https://github.com/michelson/chaskiq/wiki/Configure-application 

tell me how it goes, 

best!
